# Welcome to Serverless!
#
# This file is the main config file for your service.
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: todoapp

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

plugins:
  - serverless-offline
# you can overwrite defaults here
#  stage: dev
#  region: us-east-1

functions:
  hello:
    handler: handler.hello

    events:
      - httpApi:
          path: /health
          method: get
  
  createUser:
    handler: user.createUser

    events:
      - httpApi:
          path: /user
          method: put
